/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Wort = 11;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int A = 1;
  /** Lexical state. */
  int END = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"a\"",
    "\"b\"",
    "\"a\"",
    "\"b\"",
    "\"a\"",
    "\"b\"",
    "\".\"",
  };

}
