PARSER_BEGIN(Parser)

public class Parser {
   public static void main(String[] args) throws Exception {
        Parser parser = new Parser(System.in);
	parser.S();
    }
}

PARSER_END(Parser)

SKIP:  { " " | "\t" | "\r"                    }
TOKEN: { "(" | ")" | "+" | "*" | <NUM: (["0"-"9"])+> }

void S(): {}
{
  E() "\n" 
}

void E(): {}
{
  T() ("+" T() )* 
}

void T(): {}
{
  F() ("*" F() )* 
}

void F(): {}
{
  <NUM> 
|
  "(" E() ")" 
}